-- PostgreSQL schema expected by the consumer worker.

CREATE TABLE IF NOT EXISTS public.voice_bot_call_job
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    external_id uuid NOT NULL DEFAULT gen_random_uuid(),
    service_id integer NOT NULL,
    correlation_id uuid NOT NULL,
    job_status character varying(30) NOT NULL DEFAULT 'PENDING',
    callback_received boolean NOT NULL DEFAULT false,
    callback_payload_file_path text,
    created_at timestamp(6) without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at timestamp(6) without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT voice_bot_call_job_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.voice_bot_call_job_event
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_id bigint NOT NULL,
    event_status character varying(20) NOT NULL,
    system_message character varying(500),
    event_occurred_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT voice_bot_call_job_event_pkey PRIMARY KEY (id),
    CONSTRAINT fk_call_job_event_job FOREIGN KEY (job_id)
        REFERENCES public.voice_bot_call_job (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS ix_voice_bot_call_job_service_id
    ON public.voice_bot_call_job (service_id);

CREATE INDEX IF NOT EXISTS ix_voice_bot_call_job_correlation_id
    ON public.voice_bot_call_job (correlation_id);

CREATE INDEX IF NOT EXISTS ix_voice_bot_call_job_event_job_id
    ON public.voice_bot_call_job_event (job_id);
