-- PostgreSQL schema creation for dev-voice-db
-- Source: Dev_voice_db2.sql
-- Run after 01_create_database.sql while connected to dev-voice-db.

BEGIN;

CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE public.language (
    id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL,
    code character varying(5) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_language_name UNIQUE (name),
    CONSTRAINT uq_language_code UNIQUE (code)
);

CREATE TABLE public.driver (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(20) NOT NULL,
    preferred_language_id smallint NOT NULL,
    language_source character varying(10) DEFAULT 'default'::character varying NOT NULL,
    do_not_call boolean DEFAULT false NOT NULL,
    created_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    CONSTRAINT ck_driver_language_source CHECK (
        language_source IN ('default', 'manual', 'detected')
    ),
    CONSTRAINT ck_driver_phone_e164 CHECK (
        phone::text ~ '^\\+[1-9][0-9]{7,14}$'
    ),
    CONSTRAINT uq_driver_external_id UNIQUE (external_id),
    CONSTRAINT uq_driver_phone UNIQUE (phone),
    CONSTRAINT fk_driver_language FOREIGN KEY (preferred_language_id)
        REFERENCES public.language(id)
);

CREATE TABLE public.vehicle (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    registration_no character varying(20) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    driver_id bigint,
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT uq_vehicle_registration_no UNIQUE (registration_no),
    CONSTRAINT fk_vehicle_driver FOREIGN KEY (driver_id)
        REFERENCES public.driver(id)
);

CREATE TABLE public.vehicle_assignment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id bigint NOT NULL,
    driver_id bigint NOT NULL,
    assigned_from timestamp with time zone DEFAULT now() NOT NULL,
    assigned_to timestamp with time zone,
    created_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    CONSTRAINT ck_assignment_period CHECK (
        assigned_to IS NULL OR assigned_to > assigned_from
    ),
    CONSTRAINT vehicle_assignment_vehicle_id_fkey FOREIGN KEY (vehicle_id)
        REFERENCES public.vehicle(id),
    CONSTRAINT vehicle_assignment_driver_id_fkey FOREIGN KEY (driver_id)
        REFERENCES public.driver(id)
);

CREATE TABLE public.vehicle_service (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    vehicle_id bigint NOT NULL,
    due_maintenance_date date NOT NULL,
    maintenance_type character varying(50) NOT NULL,
    service_status character varying(20) DEFAULT 'DUE'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    call_attempts integer DEFAULT 0 NOT NULL,
    CONSTRAINT fk_vehicle_service_vehicle FOREIGN KEY (vehicle_id)
        REFERENCES public.vehicle(id)
);

CREATE TABLE public.voice_bot_call_job (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid DEFAULT gen_random_uuid() NOT NULL,
    service_id integer NOT NULL,
    correlation_id uuid NOT NULL,
    job_status character varying(30) DEFAULT 'PENDING'::character varying NOT NULL,
    callback_received boolean DEFAULT false NOT NULL,
    callback_payload_file_path text,
    created_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text) NOT NULL,
    CONSTRAINT fk_voice_bot_call_job_service FOREIGN KEY (service_id)
        REFERENCES public.vehicle_service(id)
);

CREATE TABLE public.voice_bot_call_job_event (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL,
    event_status character varying(20) NOT NULL,
    system_message character varying(500),
    event_occurred_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_call_job_event_job FOREIGN KEY (job_id)
        REFERENCES public.voice_bot_call_job(id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX ix_driver_language
    ON public.driver USING btree (preferred_language_id);

CREATE INDEX ix_assignment_driver
    ON public.vehicle_assignment USING btree (driver_id);

CREATE UNIQUE INDEX uq_assignment_one_current
    ON public.vehicle_assignment USING btree (vehicle_id)
    WHERE assigned_to IS NULL;

CREATE INDEX ix_vehicle_service_vehicle
    ON public.vehicle_service USING btree (vehicle_id);

CREATE INDEX ix_voice_bot_call_job_correlation
    ON public.voice_bot_call_job USING btree (correlation_id);

CREATE INDEX ix_voice_bot_call_job_service
    ON public.voice_bot_call_job USING btree (service_id);

CREATE INDEX ix_voice_bot_call_job_event_job
    ON public.voice_bot_call_job_event USING btree (job_id);

CREATE INDEX ix_voice_bot_call_job_event_status
    ON public.voice_bot_call_job_event USING btree (event_status);

-- PostgreSQL exclusion constraint: one vehicle cannot have overlapping assignments.
ALTER TABLE ONLY public.vehicle_assignment
    ADD CONSTRAINT ex_vehicle_assignment_no_overlap
    EXCLUDE USING gist (
        vehicle_id WITH =,
        tstzrange(assigned_from, assigned_to, '[)') WITH &&
    );

-- ============================================================
-- FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION public.normalize_in_phone(p text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE
        WHEN d ~ '^[6-9][0-9]{9}$'
            THEN '+91' || d
        WHEN d ~ '^91[6-9][0-9]{9}$'
            THEN '+' || d
        WHEN d ~ '^0[6-9][0-9]{9}$'
            THEN '+91' || substr(d, 2)
        ELSE NULL
    END
    FROM (
        SELECT regexp_replace(
            coalesce(p, ''),
            '\\D',
            '',
            'g'
        ) AS d
    ) s;
$$;

CREATE OR REPLACE FUNCTION public.assign_vehicle(
    p_vehicle_id bigint,
    p_driver_id bigint,
    p_at timestamp with time zone DEFAULT now()
)
RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
    v_current_id     bigint;
    v_current_driver bigint;
    v_new_id         bigint;
BEGIN
    SELECT id, driver_id
    INTO v_current_id, v_current_driver
    FROM public.vehicle_assignment
    WHERE vehicle_id = p_vehicle_id
      AND assigned_to IS NULL
    FOR UPDATE;

    -- Already assigned to this driver.
    IF v_current_id IS NOT NULL
       AND v_current_driver = p_driver_id THEN
        RETURN v_current_id;
    END IF;

    -- Close previous assignment.
    IF v_current_id IS NOT NULL THEN
        UPDATE public.vehicle_assignment
        SET assigned_to = p_at
        WHERE id = v_current_id;
    END IF;

    -- Create new assignment.
    INSERT INTO public.vehicle_assignment
    (
        vehicle_id,
        driver_id,
        assigned_from
    )
    VALUES
    (
        p_vehicle_id,
        p_driver_id,
        p_at
    )
    RETURNING id INTO v_new_id;

    RETURN v_new_id;
END;
$$;

-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW public.v_pms_call_queue AS
SELECT
    vs.id AS vehicle_service_id,
    vs.external_id AS service_external_id,
    vs.due_maintenance_date,
    vs.maintenance_type,
    vs.call_attempts,
    v.id AS vehicle_id,
    v.registration_no,
    d.id AS driver_id,
    d.name AS driver_name,
    d.phone AS driver_phone,
    l.id AS language_id,
    l.code AS preferred_language,
    l.name AS preferred_language_name,
    d.language_source
FROM public.vehicle_service vs
JOIN public.vehicle v
    ON v.id = vs.vehicle_id
JOIN public.vehicle_assignment a
    ON a.vehicle_id = v.id
   AND a.assigned_to IS NULL
JOIN public.driver d
    ON d.id = a.driver_id
JOIN public.language l
    ON l.id = d.preferred_language_id
WHERE vs.service_status = 'DUE'
  AND d.do_not_call = false;

CREATE OR REPLACE VIEW public.v_pms_needs_attention AS
SELECT
    vs.id AS vehicle_service_id,
    v.registration_no,
    vs.due_maintenance_date,
    CASE
        WHEN a.id IS NULL THEN 'no current driver'::text
        WHEN d.do_not_call THEN 'driver is do_not_call'::text
        ELSE NULL::text
    END AS reason
FROM public.vehicle_service vs
JOIN public.vehicle v
    ON v.id = vs.vehicle_id
LEFT JOIN public.vehicle_assignment a
    ON a.vehicle_id = v.id
   AND a.assigned_to IS NULL
LEFT JOIN public.driver d
    ON d.id = a.driver_id
WHERE vs.service_status = 'DUE'
  AND (a.id IS NULL OR d.do_not_call);

COMMIT;
